Khan/actions

.changeset/breezy-news-greet.md, .github/workflows/node-ci.yml, actions/get-changed-files/action.yml, actions/get-changed-files/index.js, actions/get-changed-files/package.json, utils/build.mjs, utils/build.test.mjs
We've unified around json encoding to deal with spaces, and we only ever ask for added_modified and renamed, so I merged them together.
This is my first time trying `actions/github-script` with a local require, and it turns out it's relative to the repo base (which makes sense). Because of this, I had to change `build.mjs` to turn `require('./actions/get-changed-files/index.js')` into `require('./index.js')` when publishing these actions individually.
See the check on this one!
=> Bring "@jaredly/get-changed-files" into our actions monorepo, stripping it down to only what we need

.changeset/silver-phones-collect.md, .github/workflows/node-ci.yml, actions/filter-files/action.yml
This allows you to filter-out paths instead of filtering for them. To used in check-for-changeset.
see example workflow
=> Add 'invert' option to filter-files

.changeset/quiet-mails-attack.md, actions/gerald-pr/action.yml
We /could/ fix this by putting an `if` on all of the gerald workflows in all of the repos, but this will fix it centrally for all.
Make a draft PR off of this one, see that the "gerald" step is skipped, and doesn't auto-assign reviewers
https://github.com/Khan/actions/pull/28 yay
=> Skip gerald steps if the PR is a draft

.changeset/weak-parrots-refuse.md, .github/workflows/keeper.yml, actions/setup-keeper/action.yml, actions/setup-keeper/package.json
The mobile keeper setup is breaking, and webapp wants to start using keeper in github actions, so might as well make something shared.
Where did KEEPER_CONFIG come from?
Make this as a local file on your machine, e.g. keeper-config.json
```json
{
"server": "keepersecurity.com",
"user": "[the keeper username that we use for jenkins]",
"password": "[the password for jenkins keeper account]",
"private_key": "",
"device_token": "",
"clone_code": ""
}
```
Then run:
```bash
$ keeper --config keeper-config.json shell
> # (you'll have some SSO rigamarole, make sure to open a private window so you can login as our jenkins account; the google password for this account is also in keeper)
My Vault> this-device register
My Vault> this-device persistent-login on
My Vault> this-device ip-auto-approve on …
```
=> Add 'setup-keeper' action for setting up keeper with authentication

.changeset/brown-crabs-vanish.md, .github/workflows/keeper.yml, actions/setup-keeper/action.yml
For some inscrutable reason, using the bash HEREDOC stuff worked a couple of times, and then never again. I trust javascript more anyway, so I'm happy with this change.
see the check working!
=> Make setup-keeper action less flaky

.changeset/young-points-sell.md, .github/workflows/gerald-pr.yml, .github/workflows/keeper.yml, .github/workflows/node-ci.yml, .github/workflows/release.yml, actions/gerald-pr/action.yml, actions/shared-node-cache/action.yml
This updates to use the latest actions and therefore remove the Node 12 dependency that is soon to not even be supported by GitHub Actions.
Issue: FEI-4813
Put this up, check things are OK. Then update and check the things that use this thing.
=> Update to use latest actions, removing Node12 dep

.changeset/nervous-owls-grin.md, actions/gerald-pr/action.yml
🖍 _This is an audit!_ 🖍
I updated gerald and actions started breaking. I suspect it's because these actions use `gerald@main` instead of a specific tag version. This PR pins gerald to a specific tag version.
Issue: FEI-4813
Do a release and update workflows to hopefully see things working again.
=> [🔥AUDIT🔥] Pin gerald at a specific tag version

.changeset/rich-waves-refuse.md, .changeset/spotty-jeans-agree.md, actions/check-for-changeset/action.yml, actions/check-for-changeset/package.json, actions/filter-files/action.yml, actions/filter-files/index.js, actions/filter-files/package.json, yarn.lock
The check-for-changeset action is really useful in making sure we don't put up a PR without a `.changeset/*` file. But it often flags PRs that we can guarantee don't need a changeset (for example, a test-only PR or one that just touches Storybook stories). 
This PR adds the ability to filter out entire classes of files by extension (*.test.js or *.stories.js) for example. 
We will still need to configure each repo that uses this action to exclude the files by extension, but this opens the door for those configurations.
Issue: "none"
Use the action in this PR in a repo (Khan/perseus, for example) and create a PR that contains changes only to files with extensions we configure to exclude.
=> Allow check-for-changeset to be configured to exclude files by extension

.changeset/rich-waves-refuse.md, .changeset/spotty-jeans-agree.md, .eslintrc.js, .github/workflows/release.yml, actions/check-for-changeset/action.yml, actions/check-for-changeset/package.json, actions/filter-files/action.yml, actions/filter-files/index.js, actions/filter-files/package.json, package.json, utils/build.mjs, utils/publish.mjs, yarn.lock
In the last Version Packages PR I had a change that added a npm dependency to one of the JS-based actions in this repo and that [broke](https://github.com/Khan/actions/actions/runs/4963419816/jobs/8882640617) the publish step!  We currently don't support this and so the publish step failed for (for two reasons actually):
1. Our build script assumes that all `dependencies` in our actions `package.json` are a cross-reference to another action in this repo
2. We don't have any bundling setup so our JS actions are copied as-is into the `dist` folder that we publish
This PR addresses both of these issues by:
1. We don't try to process depedencies in action YML files for external deps
2. Set up ncc to build JS packages on publish (following Github [JS action …
=> Support JS-based actions having dependencies

.changeset/spotty-kangaroos-glow.md, actions/check-for-changeset/action.yml
When I added the `exclude_extensions` parameter to the `check-for-changeset` action.yml, I accidentally had two dollar signs when accessing the `exclude_extensions` input parameter (ie. `$${{ input.exclude_extensions }}`). This then caused the `check-for-changeset` to complain about changesets when it shouldn't ([here](https://github.com/Khan/perseus/actions/runs/4985308846/jobs/8924746558?pr=531))
This caused the call to `filter-files` to have an `extensions` value that always started with a dollar sign, which in turn caused the provided extension list to not match if the file _would have_ matched the first extension in the list (because the `filter-files` action got a list of extensions that looked like this: `['$.ext1', '.ext2', '.ext3']`. 
Issue: "none"
I'll land this and publish and …
=> [🔥AUDIT🔥] Fix exclude_extensions in check-for-changeset action call

.changeset/selfish-spoons-retire.md, actions/shared-node-cache/action.yml, utils/publish.mjs
🖍 _This is an audit!_ 🖍
It has been publishing our actions correctly, but then the `changesets/action` fails, and so the "github action" technically errors out (see https://github.com/Khan/actions/actions/runs/4982973373/jobs/8919388693)
It would be nice for that not to be the case.
The thing that's happening is the changesets/action tries to `git push origin --tags`, and that's failing for some reason. I'll try doing it already within our script, to see if any good will come of it.
=> [🔥AUDIT🔥] Try to fix our publish script

.changeset/good-snails-walk.md, actions/setup-keeper/action.yml
Keeper is throttling our API calls, preventing our GitHub Actions from
deploying ZNDs for webapp PRs. See this Slack thread for discussion:
https://khanacademy.slack.com/archives/C02NMB1R5/p1685030740156649
Changing the keepercommander version seems to fix the throttling issue,
somehow.
Note: the previous release of setup-keeper, 1.1.0, changed the version
of keepercommander to 16.5.6. That was due to a miscommunication; 16.5.6
will not work in webapp. During the "Deploy static version to GCS" step
of running E2E tests, we get this error:
```
KeeperError: keeper version 16.5.6 is too old, see https://khanacademy.org/r/keeper-cli for assistance
at _verifyKeeperInstallation (/home/runner/work/webapp/webapp/services/static/dev/tools/utils/map-keeper-records.js:75:15)
```
Issue: none
Run the …
=> Upgrade keepercommander to 16.5.16

.changeset/twenty-cougars-remain.md, actions/get-changed-files/action.yml
`token` input is unused, but marked `required`. This creates some noisy red underlines in consuming workflows that use the Github Actions extension.
=> Remove superfluous input

.changeset/selfish-cheetahs-compare.md, .github/workflows/node-ci.yml, actions/filter-files/action.yml, actions/filter-files/filter-files.test.mjs, actions/filter-files/index.js
Adds option to assert _all_ filters pass.
Currently, if any of the filters are true, the path is included in filtered files. This makes it difficult to use multiple filter types to refine our choice, especially when not in `invert` mode.
Now, we can designate some directories and file extensions and only files in those directories with those extensions will return.
=> Allow Conjunctive Filter (all true, vs current any true)

.changeset/olive-eyes-pull.md, actions/shared-node-cache/action.yml
This changes the default node version for the shared-node-cache action to 20. Did this as a major bump so that repos that didn't specify a version other than the default aren't going to get a surprise bump to 20. That way we can do things repo-by-repo to head of any weird issues.
Issue: FEI-5413
1. `yarn lint`
2. `yarn test`
3. Get this release published and then we can start using it in the repos I migrate to Node 20, and verify all is well.
=> Move to Node 20 being our default

.changeset/poor-crabs-march.md, .github/workflows/gerald-pr.yml, .github/workflows/node-ci.yml, .github/workflows/release.yml, actions/check-for-changeset/action.yml, actions/filter-files/action.yml, actions/gerald-pr/action.yml, actions/get-changed-files/action.yml, actions/json-args/action.yml, actions/shared-node-cache/action.yml, utils/build.test.mjs
This updates all the workflows to use actions that are running on Node 20 instead of 16.
Issue: FEI-5484
`yarn test`
=> Update to Node20-ready action versions

.changeset/long-ears-act.md, actions/gerald-pr/action.yml
This updates the `gerald-pr` action to use the latest Khan/gerald release, supporting Node 20, and the repo version of `get-changed-files` so that it will be up-to-date on each release.
Issue: FEI-5545
`yarn test`
Update consumers of this action to use the new version and see that they no longer warn of Node 16 deprecation.
=> Update gerald action to Node 20

.changeset/slow-colts-sell.md, actions/gerald-pr/package.json
🖍 _This is an audit!_ 🖍
I missed this step when I updated gerald-pr action to reference the repo version of get-changed-files. This PR adds that dependency so our build tooling will do the proper thing when releasing.
Issue: FEI-5545
Put this up and look at the generated action.yml for the tagged gerald-pr release to make sure it has replaced the local reference with a versioned reference.
=> [🔥AUDIT🔥] Make sure we have get-changed-files in the gerald-pr deps

.changeset/cuddly-poets-listen.md, README.md, actions/gerald-pr/action.yml
See [this PR](https://github.com/Khan/gerald/pull/87) with a bug-fix regarding GitHub teams not getting added when author is a member of that team, and the author adds comments. Point this to that, once it's landed and tagged.
I also updated the README with instructions (mostly for myself, because I forgot what I did last time) on how to test PRs in this repo _before_ landing (and publishing).
=> Bumping actions/gerald-pr to point to newer version of Khan/gerald

actions/gerald-pr/CHANGELOG.md, actions/gerald-pr/action.yml, actions/gerald-pr/package.json
Boy this is a complex workflow!  Here's what I needed to do:
1. Create a `v5` tag in Khan/gerald, pointing to the new code
2. Change action.yml here to point to Khan/gerald@v5
3. Land this
4. Push a tag call gerald-pr-v5 that points to the new HEAD here
5. Update webapp's .github/actions/gerald-pr.yml to point to gerald-pr-v5
Issue: https://khanacademy.atlassian.net/browse/FEI-5970
Fingers crossed
=> Update gerald-pr to point to the new v5 version.

.changeset/nervous-actors-tell.md, .github/workflows/node-ci.yml, actions/shared-node-cache/action.yml
In the last PR I added a `ssh-private-key` input to the `shared-node-cache` action. However, this isn't needed/used in all cases and so making it required breaks some existing usages. I've made it optional now and only run the `webfactory/ssh-agent` action if a key has been provided. 
Issue: --none--
Watch the actions. The `shared-node-cache` action is run in this repo as part of PR checks. That run is now set up to _not_ provide an `ssh-private-key`. I'll verify that it works _with_ an `ssh-private-key` after landing and integrating in another repo.
=> Allow running shared-node-cache without ssh-private-key

.changeset/dry-pears-sing.md, .github/workflows/node-ci.yml, actions/filter-files/action.yml, actions/filter-files/filter-files.test.mjs, actions/filter-files/index.js
I'm going to be using a rather lengthy set of glob filters for the deploy workflow in the frontend repo, and I want the ability to separate them into sections with.
Issue: FEI-XXXX
see tests
=> Filter out comment lines in inputs

.changeset/weak-beans-sniff.md, actions/filter-files/filter-files.test.mjs, actions/filter-files/index.js
The current behavior of negative globs only makes sense if `matchAllGlobs` is true. If it's false, then weird things happen. For example:
```
input files:
- one/two.js
- one/two/three.test.ts
- one/two.json
globs:
one/**
!**/*.test.ts
!**/*.json
```
The behavior is "a file 'matches' if any of the globs match". As you can see in this case, given two negative non-intersecting globs, all files will always match, because at least one of them will match for every file.
I'm changing it so that if `matchAllGlobs` is false, then the behavior is: "all negative globs have to match, and at least one positive glob needs to match".
With this, the result of the above example would be `one/two.js`, which I think is intuitive.
Issue: none
See the test I added.
=> Change behavior of "negative globs" to match .gitignore

.changeset/sour-streets-mix.md, actions/get-changed-files/index.js
yay merge groups
Issue: none
in order to test it I'll need to run it on a repo that has a merge queue, which I don't want to set up for this repo at the moment 😬
=> Add `merge_group` event support to the get-changed-files action

.changeset/five-camels-tap.md, .github/workflows/node-ci.yml, actions/filter-files/action.yml
It's a very common pattern to do `steps.changed-files.outputs.filtered != '[]'`, and this will make it cleaner.
Issue: none
see node-ci.yml
=> Add a `matched_any` output to filter-files
